- name: Setup Redis Server
  hosts: server_role_redis_server
  become: true
  remote_user: rocky
  roles:
    - rocky

- name: Setup Frontend Server
  hosts: server_role_frontend_server
  become: true
  remote_user: ubuntu
  roles:
    - ubuntu
